# SCADA Simulator
#
# Copyright 2018 Carnegie Mellon University. All Rights Reserved.
#
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
#
# Released under a MIT (SEI)-style license, please see license.txt or contact permission@sei.cmu.edu for full terms.
#
# [DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.  Please see Copyright notice for non-US Government use and distribution.
# This Software includes and/or makes use of the following Third-Party Software subject to its own license:
# 1. Packery (https://packery.metafizzy.co/license.html) Copyright 2018 metafizzy.
# 2. Bootstrap (https://getbootstrap.com/docs/4.0/about/license/) Copyright 2011-2018  Twitter, Inc. and Bootstrap Authors.
# 3. JIT/Spacetree (https://philogb.github.io/jit/demos.html) Copyright 2013 Sencha Labs.
# 4. html5shiv (https://github.com/aFarkas/html5shiv/blob/master/MIT%20and%20GPL2%20licenses.md) Copyright 2014 Alexander Farkas.
# 5. jquery (https://jquery.org/license/) Copyright 2018 jquery foundation.
# 6. CanvasJS (https://canvasjs.com/license/) Copyright 2018 fenopix.
# 7. Respond.js (https://github.com/scottjehl/Respond/blob/master/LICENSE-MIT) Copyright 2012 Scott Jehl.
# 8. Datatables (https://datatables.net/license/) Copyright 2007 SpryMedia.
# 9. jquery-bridget (https://github.com/desandro/jquery-bridget) Copyright 2018 David DeSandro.
# 10. Draggabilly (https://draggabilly.desandro.com/) Copyright 2018 David DeSandro.
# 11. Business Casual Bootstrap Theme (https://startbootstrap.com/template-overviews/business-casual/) Copyright 2013 Blackrock Digital LLC.
# 12. Glyphicons Fonts (https://www.glyphicons.com/license/) Copyright 2010 - 2018 GLYPHICONS.
# 13. Bootstrap Toggle (http://www.bootstraptoggle.com/) Copyright 2011-2014 Min Hur, The New York Times.
# DM18-1351
#

MASTER:
  num_of_PLC: 4
PLC 0:
  DATASTORE:
    co:
      start_addr: 1
      values:
      - 0
      behavior_1: {'type': 'none'}
    di:
      start_addr: 1
      values:
      - 1
    hr:
      start_addr: 1
      values:
      - 100
      behavior_1: {'type': 'fuel_tank_behavior', 'min': 0, 'max': 100, 'address': 0x00, 'time': 0, 'count': 1, 'coil_address': 0x00}
    ir:
      start_addr: 1
      values:
      - 0
  LOGGING:
    file: /usr/local/bin/scadasim_pymodbus_plc/logging/logging_0.log
    format: '%(asctime)-15s %(threadName)-15s %(levelname)-8s %(module)-15s:%(lineno)-8s
    %(message)s'
    logging_level: DEBUG
  SERVER:
    framer: TCP
    port: 502
    type: tcp
    address: 10.0.2.9
PLC 1:
  DATASTORE:
    co:
      start_addr: 1
      values:
      - 0
      behavior_1: {'type': 'none'}
    di:
      start_addr: 1
      values:
      - 0
    hr:
      start_addr: 1
      values:
      - 90
      behavior_1: {'type': 'random', 'min': 0, 'max': 5, 'address': 0x00, 'time': 5, 'count': 1}
    ir:
      start_addr: 1
      values:
      - 0
  LOGGING:
    file: /usr/local/bin/scadasim_pymodbus_plc/logging/logging_1.log
    format: '%(asctime)-15s %(threadName)-15s %(levelname)-8s %(module)-15s:%(lineno)-8s
    %(message)s'
    logging_level: INFO
  SERVER:
    framer: TCP
    port: 502
    type: tcp
    address: 10.0.2.10
PLC 2:
  DATASTORE:
    co:
      start_addr: 1
      values:
      - 0
      behavior_1: {'type': 'none'}
    di:
      start_addr: 1
      values:
      - 0
    hr:
      start_addr: 1
      values:
      - 100
      behavior_1: {'type': 'fuel_tank_behavior', 'min': 0, 'max': 100, 'address': 0x00, 'time': 0, 'count': 1, 'coil_address': 0x00}
    ir:
      start_addr: 1
      values:
      - 0
  LOGGING:
    file: /usr/local/bin/scadasim_pymodbus_plc/logging/logging_2.log
    format: '%(asctime)-15s %(threadName)-15s %(levelname)-8s %(module)-15s:%(lineno)-8s
    %(message)s'
    logging_level: INFO
  SERVER:
    framer: TCP
    port: 502
    type: tcp
    address: 10.0.2.11
PLC 3:
  DATASTORE:
    co:
      start_addr: 1
      values:
      - 0
      behavior_1: {'type': 'none'}
    di:
      start_addr: 1
      values:
      - 0
    hr:
      start_addr: 1
      values:
      - 90
      behavior_1: {'type': 'random', 'min': 0, 'max': 5, 'address': 0x00, 'time': 5, 'count': 1}
    ir:
      start_addr: 1
      values:
      - 0
  LOGGING:
    file: /usr/local/bin/scadasim_pymodbus_plc/logging/logging_3.log
    format: '%(asctime)-15s %(threadName)-15s %(levelname)-8s %(module)-15s:%(lineno)-8s
    %(message)s'
    logging_level: INFO
  SERVER:
    framer: TCP
    port: 502
    type: tcp
    address: 10.0.2.12
